### ISSUE TITLE
Working with Pydoop 1.0

### ISSUE THREAD

**Issue by jmabuin** [crs4/seal#6]
It didn't work for me with Pydoop 1.0rc1 and hadoop 2.6.0 until I modified file seal/seqal/seqal_run.py

I had to add **pydoop_argv.append("--module")** before **pydoop_argv.append("seal.seqal.seqal_run")**

As I am not familiarized with your code or Pydoop I didn't want to make a pull request. I will be gratefull if you tell me if this solution I am proposing is correct.

**Comment by ilveroluca** [comment]
Hi!  Thanks for looking into this.  I think the problem is that there were some small changes in `pydoop submit` between 1.0rc1 and 1.0.0.  If you update your Pydoop installation to 1.0.0 the Seal master should work fine.  Let me know if it isn't so.

**Comment by jmabuin** [comment]
Ok, I will try, thank you very much Luca :)
